markdown: kramdown

title: Lendlag AS
description: Lendlag Landing Page

theme: minima

# Minima: show excerpts in the frontpage
show_excerpts: false

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages: []

exclude: 
    - .gitignore
    - docker-compose.yml
    - LICENSE
    - README.md
